### ISSUE TITLE
Don't recreate the fragment whenever view model is updated

### ISSUE THREAD

**Issue by akench** [SChakravorti21/SakaiClientAndroid#29]
This will waste a lot of resources recreating the fragment every time. If possible, more the observation into the fragment class itself so it can just recreate the treeview/recycler view and fill it with the new data.

**Comment by SChakravorti21** [comment]
This has (mostly) been fixed with PR #35, where we moved most `LiveData` observations into the fragments themselves, with dynamic updates to the `TreeViews`. This also greatly simplified the `MainActivity` since it does not need to do as many `LiveData` observations now (the only one left is with announcements, which is a slightly more complicated use-case, and we'll probably use `MediatorLiveData` to account for it).
